// Generated by gencpp from file pkg_task2/vacuumGripper.msg
// DO NOT EDIT!


#ifndef PKG_TASK2_MESSAGE_VACUUMGRIPPER_H
#define PKG_TASK2_MESSAGE_VACUUMGRIPPER_H

#include <ros/service_traits.h>


#include <pkg_task2/vacuumGripperRequest.h>
#include <pkg_task2/vacuumGripperResponse.h>


namespace pkg_task2
{

struct vacuumGripper
{

typedef vacuumGripperRequest Request;
typedef vacuumGripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vacuumGripper
} // namespace pkg_task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_task2::vacuumGripper > {
  static const char* value()
  {
    return "22dce99b1d1e31fc9ba6b2faee126298";
  }

  static const char* value(const ::pkg_task2::vacuumGripper&) { return value(); }
};

template<>
struct DataType< ::pkg_task2::vacuumGripper > {
  static const char* value()
  {
    return "pkg_task2/vacuumGripper";
  }

  static const char* value(const ::pkg_task2::vacuumGripper&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_task2::vacuumGripperRequest> should match
// service_traits::MD5Sum< ::pkg_task2::vacuumGripper >
template<>
struct MD5Sum< ::pkg_task2::vacuumGripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_task2::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_task2::vacuumGripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_task2::vacuumGripperRequest> should match
// service_traits::DataType< ::pkg_task2::vacuumGripper >
template<>
struct DataType< ::pkg_task2::vacuumGripperRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_task2::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_task2::vacuumGripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_task2::vacuumGripperResponse> should match
// service_traits::MD5Sum< ::pkg_task2::vacuumGripper >
template<>
struct MD5Sum< ::pkg_task2::vacuumGripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_task2::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_task2::vacuumGripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_task2::vacuumGripperResponse> should match
// service_traits::DataType< ::pkg_task2::vacuumGripper >
template<>
struct DataType< ::pkg_task2::vacuumGripperResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_task2::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_task2::vacuumGripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_TASK2_MESSAGE_VACUUMGRIPPER_H
