// Generated by gencpp from file pkg_task2/vacuumGripperRequest.msg
// DO NOT EDIT!


#ifndef PKG_TASK2_MESSAGE_VACUUMGRIPPERREQUEST_H
#define PKG_TASK2_MESSAGE_VACUUMGRIPPERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_task2
{
template <class ContainerAllocator>
struct vacuumGripperRequest_
{
  typedef vacuumGripperRequest_<ContainerAllocator> Type;

  vacuumGripperRequest_()
    : activate_vacuum_gripper(false)  {
    }
  vacuumGripperRequest_(const ContainerAllocator& _alloc)
    : activate_vacuum_gripper(false)  {
  (void)_alloc;
    }



   typedef uint8_t _activate_vacuum_gripper_type;
  _activate_vacuum_gripper_type activate_vacuum_gripper;





  typedef boost::shared_ptr< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> const> ConstPtr;

}; // struct vacuumGripperRequest_

typedef ::pkg_task2::vacuumGripperRequest_<std::allocator<void> > vacuumGripperRequest;

typedef boost::shared_ptr< ::pkg_task2::vacuumGripperRequest > vacuumGripperRequestPtr;
typedef boost::shared_ptr< ::pkg_task2::vacuumGripperRequest const> vacuumGripperRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator1> & lhs, const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator2> & rhs)
{
  return lhs.activate_vacuum_gripper == rhs.activate_vacuum_gripper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator1> & lhs, const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_task2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "751b0bcd7e7e984c5083f65904bb71f9";
  }

  static const char* value(const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x751b0bcd7e7e984cULL;
  static const uint64_t static_value2 = 0x5083f65904bb71f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_task2/vacuumGripperRequest";
  }

  static const char* value(const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool activate_vacuum_gripper\n"
;
  }

  static const char* value(const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.activate_vacuum_gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vacuumGripperRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_task2::vacuumGripperRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_task2::vacuumGripperRequest_<ContainerAllocator>& v)
  {
    s << indent << "activate_vacuum_gripper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.activate_vacuum_gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_TASK2_MESSAGE_VACUUMGRIPPERREQUEST_H
